#define PyMem_Malloc ((void*(*)(size_t))imports[0].proc)
#define PyMem_Realloc ((void*(*)(void *, size_t))imports[1].proc)
#define PyMem_Free ((void(*)(void *))imports[2].proc)
#define PyType_IsSubtype ((int(*)(PyTypeObject *, PyTypeObject *))imports[3].proc)
#define PyType_Ready ((int(*)(PyTypeObject *))imports[4].proc)
#define PyType_GenericAlloc ((PyObject*(*)(PyTypeObject *, Py_ssize_t))imports[5].proc)
#define PyType_GenericNew ((PyObject*(*)(PyTypeObject *, PyObject *, PyObject *))imports[6].proc)
#define _PyType_Lookup ((PyObject*(*)(PyTypeObject *, PyObject *))imports[7].proc)
#define _PyObject_LookupSpecial ((PyObject*(*)(PyObject *, char *, PyObject **))imports[8].proc)
#define PyType_ClearCache ((unsigned int(*)(void))imports[9].proc)
#define PyType_Modified ((void(*)(PyTypeObject *))imports[10].proc)
#define PyObject_Print ((int(*)(PyObject *, FILE *, int))imports[11].proc)
#define _PyObject_Dump ((void(*)(PyObject *))imports[12].proc)
#define PyObject_Repr ((PyObject*(*)(PyObject *))imports[13].proc)
#define _PyObject_Str ((PyObject*(*)(PyObject *))imports[14].proc)
#define PyObject_Str ((PyObject*(*)(PyObject *))imports[15].proc)
#define PyObject_Unicode ((PyObject*(*)(PyObject *))imports[16].proc)
#define PyObject_Compare ((int(*)(PyObject *, PyObject *))imports[17].proc)
#define PyObject_RichCompare ((PyObject*(*)(PyObject *, PyObject *, int))imports[18].proc)
#define PyObject_RichCompareBool ((int(*)(PyObject *, PyObject *, int))imports[19].proc)
#define PyObject_GetAttrString ((PyObject*(*)(PyObject *, const char *))imports[20].proc)
#define PyObject_SetAttrString ((int(*)(PyObject *, const char *, PyObject *))imports[21].proc)
#define PyObject_HasAttrString ((int(*)(PyObject *, const char *))imports[22].proc)
#define PyObject_GetAttr ((PyObject*(*)(PyObject *, PyObject *))imports[23].proc)
#define PyObject_SetAttr ((int(*)(PyObject *, PyObject *, PyObject *))imports[24].proc)
#define PyObject_HasAttr ((int(*)(PyObject *, PyObject *))imports[25].proc)
#define _PyObject_GetDictPtr ((PyObject**(*)(PyObject *))imports[26].proc)
#define PyObject_SelfIter ((PyObject*(*)(PyObject *))imports[27].proc)
#define _PyObject_NextNotImplemented ((PyObject*(*)(PyObject *))imports[28].proc)
#define PyObject_GenericGetAttr ((PyObject*(*)(PyObject *, PyObject *))imports[29].proc)
#define PyObject_GenericSetAttr ((int(*)(PyObject *, PyObject *, PyObject *))imports[30].proc)
#define PyObject_Hash ((long(*)(PyObject *))imports[31].proc)
#define PyObject_HashNotImplemented ((long(*)(PyObject *))imports[32].proc)
#define PyObject_IsTrue ((int(*)(PyObject *))imports[33].proc)
#define PyObject_Not ((int(*)(PyObject *))imports[34].proc)
#define PyCallable_Check ((int(*)(PyObject *))imports[35].proc)
#define PyNumber_Coerce ((int(*)(PyObject **, PyObject **))imports[36].proc)
#define PyNumber_CoerceEx ((int(*)(PyObject **, PyObject **))imports[37].proc)
#define PyObject_ClearWeakRefs ((void(*)(PyObject *))imports[38].proc)
#define _PyObject_SlotCompare ((int(*)(PyObject *, PyObject *))imports[39].proc)
#define _PyObject_GenericGetAttrWithDict ((PyObject*(*)(PyObject *, PyObject *, PyObject *))imports[40].proc)
#define _PyObject_GenericSetAttrWithDict ((int(*)(PyObject *, PyObject *, PyObject *, PyObject *))imports[41].proc)
#define PyObject_Dir ((PyObject*(*)(PyObject *))imports[42].proc)
#define Py_ReprEnter ((int(*)(PyObject *))imports[43].proc)
#define Py_ReprLeave ((void(*)(PyObject *))imports[44].proc)
#define _Py_HashDouble ((long(*)(double))imports[45].proc)
#define _Py_HashPointer ((long(*)(void *))imports[46].proc)
#define Py_IncRef ((void(*)(PyObject *))imports[47].proc)
#define Py_DecRef ((void(*)(PyObject *))imports[48].proc)
#define _PyTrash_deposit_object ((void(*)(PyObject *))imports[49].proc)
#define _PyTrash_destroy_chain ((void(*)(void))imports[50].proc)
#define PyObject_Malloc ((void*(*)(size_t))imports[51].proc)
#define PyObject_Realloc ((void*(*)(void *, size_t))imports[52].proc)
#define PyObject_Free ((void(*)(void *))imports[53].proc)
#define PyObject_Init ((PyObject*(*)(PyObject *, PyTypeObject *))imports[54].proc)
#define PyObject_InitVar ((PyVarObject*(*)(PyVarObject *, PyTypeObject *, Py_ssize_t))imports[55].proc)
#define _PyObject_New ((PyObject*(*)(PyTypeObject *))imports[56].proc)
#define _PyObject_NewVar ((PyVarObject*(*)(PyTypeObject *, Py_ssize_t))imports[57].proc)
#define PyGC_Collect ((Py_ssize_t(*)(void))imports[58].proc)
#define _PyObject_GC_Resize ((PyVarObject*(*)(PyVarObject *, Py_ssize_t))imports[59].proc)
#define _PyObject_GC_Malloc ((PyObject*(*)(size_t))imports[60].proc)
#define _PyObject_GC_New ((PyObject*(*)(PyTypeObject *))imports[61].proc)
#define _PyObject_GC_NewVar ((PyVarObject*(*)(PyTypeObject *, Py_ssize_t))imports[62].proc)
#define PyObject_GC_Track ((void(*)(void *))imports[63].proc)
#define PyObject_GC_UnTrack ((void(*)(void *))imports[64].proc)
#define PyObject_GC_Del ((void(*)(void *))imports[65].proc)
#define Py_FatalError ((void(*)(const char *message))imports[66].proc)
#define PyUnicodeUCS2_FromUnicode ((PyObject*(*)(const Py_UNICODE *u, Py_ssize_t size))imports[67].proc)
#define PyUnicodeUCS2_FromStringAndSize ((PyObject*(*)(const char *u, Py_ssize_t size))imports[68].proc)
#define PyUnicodeUCS2_FromString ((PyObject*(*)(const char *u))imports[69].proc)
#define PyUnicodeUCS2_AsUnicode ((Py_UNICODE*(*)(PyObject *unicode))imports[70].proc)
#define PyUnicodeUCS2_GetSize ((Py_ssize_t(*)(PyObject *unicode))imports[71].proc)
#define Py_UNICODEPyUnicodeUCS2_GetMax ((int(*)(void))imports[72].proc)
#define PyUnicodeUCS2_Resize ((int(*)(PyObject **unicode, Py_ssize_t length))imports[73].proc)
#define PyUnicodeUCS2_FromEncodedObject ((PyObject*(*)(register PyObject *obj, const char *encoding, const char *errors))imports[74].proc)
#define PyUnicodeUCS2_FromObject ((PyObject*(*)(register PyObject *obj))imports[75].proc)
#define PyUnicodeUCS2_FromFormatV ((PyObject*(*)(const char *, va_list))imports[76].proc)
#define PyUnicodeUCS2_FromFormat ((PyObject*(*)(const char *, ...))imports[77].proc)
#define _PyUnicode_FormatAdvanced ((PyObject*(*)(PyObject *obj, Py_UNICODE *format_spec, Py_ssize_t format_spec_len))imports[78].proc)
#define PyUnicodeUCS2_FromWideChar ((PyObject*(*)(register const wchar_t *w, Py_ssize_t size))imports[79].proc)
#define PyUnicodeUCS2_AsWideChar ((Py_ssize_t(*)(PyUnicodeObject *unicode, register wchar_t *w, Py_ssize_t size))imports[80].proc)
#define PyUnicodeUCS2_FromOrdinal ((PyObject*(*)(int ordinal))imports[81].proc)
#define PyUnicodeUCS2_ClearFreelist ((int(*)(void))imports[82].proc)
#define _PyUnicodeUCS2_AsDefaultEncodedString ((PyObject*(*)(PyObject *, const char *))imports[83].proc)
#define PyUnicodeUCS2_GetDefaultEncoding ((const char*(*)(void))imports[84].proc)
#define PyUnicodeUCS2_SetDefaultEncoding ((int(*)(const char *encoding))imports[85].proc)
#define PyUnicodeUCS2_Decode ((PyObject*(*)(const char *s, Py_ssize_t size, const char *encoding, const char *errors))imports[86].proc)
#define PyUnicodeUCS2_Encode ((PyObject*(*)(const Py_UNICODE *s, Py_ssize_t size, const char *encoding, const char *errors))imports[87].proc)
#define PyUnicodeUCS2_AsEncodedObject ((PyObject*(*)(PyObject *unicode, const char *encoding, const char *errors))imports[88].proc)
#define PyUnicodeUCS2_AsEncodedString ((PyObject*(*)(PyObject *unicode, const char *encoding, const char *errors))imports[89].proc)
#define PyUnicode_BuildEncodingMap ((PyObject*(*)(PyObject *string))imports[90].proc)
#define PyUnicode_DecodeUTF7 ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors))imports[91].proc)
#define PyUnicode_DecodeUTF7Stateful ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors, Py_ssize_t *consumed))imports[92].proc)
#define PyUnicode_EncodeUTF7 ((PyObject*(*)(const Py_UNICODE *data, Py_ssize_t length, int base64SetO, int base64WhiteSpace, const char *errors))imports[93].proc)
#define PyUnicodeUCS2_DecodeUTF8 ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors))imports[94].proc)
#define PyUnicodeUCS2_DecodeUTF8Stateful ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors, Py_ssize_t *consumed))imports[95].proc)
#define PyUnicodeUCS2_AsUTF8String ((PyObject*(*)(PyObject *unicode))imports[96].proc)
#define PyUnicodeUCS2_EncodeUTF8 ((PyObject*(*)(const Py_UNICODE *data, Py_ssize_t length, const char *errors))imports[97].proc)
#define PyUnicodeUCS2_DecodeUTF32 ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors, int *byteorder))imports[98].proc)
#define PyUnicodeUCS2_DecodeUTF32Stateful ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors, int *byteorder, Py_ssize_t *consumed))imports[99].proc)
#define PyUnicodeUCS2_AsUTF32String ((PyObject*(*)(PyObject *unicode))imports[100].proc)
#define PyUnicodeUCS2_EncodeUTF32 ((PyObject*(*)(const Py_UNICODE *data, Py_ssize_t length, const char *errors, int byteorder))imports[101].proc)
#define PyUnicodeUCS2_DecodeUTF16 ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors, int *byteorder))imports[102].proc)
#define PyUnicodeUCS2_DecodeUTF16Stateful ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors, int *byteorder, Py_ssize_t *consumed))imports[103].proc)
#define PyUnicodeUCS2_AsUTF16String ((PyObject*(*)(PyObject *unicode))imports[104].proc)
#define PyUnicodeUCS2_EncodeUTF16 ((PyObject*(*)(const Py_UNICODE *data, Py_ssize_t length, const char *errors, int byteorder))imports[105].proc)
#define PyUnicodeUCS2_DecodeUnicodeEscape ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors))imports[106].proc)
#define PyUnicodeUCS2_AsUnicodeEscapeString ((PyObject*(*)(PyObject *unicode))imports[107].proc)
#define PyUnicodeUCS2_EncodeUnicodeEscape ((PyObject*(*)(const Py_UNICODE *data, Py_ssize_t length))imports[108].proc)
#define PyUnicodeUCS2_DecodeRawUnicodeEscape ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors))imports[109].proc)
#define PyUnicodeUCS2_AsRawUnicodeEscapeString ((PyObject*(*)(PyObject *unicode))imports[110].proc)
#define PyUnicodeUCS2_EncodeRawUnicodeEscape ((PyObject*(*)(const Py_UNICODE *data, Py_ssize_t length))imports[111].proc)
#define _PyUnicode_DecodeUnicodeInternal ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors))imports[112].proc)
#define PyUnicodeUCS2_DecodeLatin1 ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors))imports[113].proc)
#define PyUnicodeUCS2_AsLatin1String ((PyObject*(*)(PyObject *unicode))imports[114].proc)
#define PyUnicodeUCS2_EncodeLatin1 ((PyObject*(*)(const Py_UNICODE *data, Py_ssize_t length, const char *errors))imports[115].proc)
#define PyUnicodeUCS2_DecodeASCII ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors))imports[116].proc)
#define PyUnicodeUCS2_AsASCIIString ((PyObject*(*)(PyObject *unicode))imports[117].proc)
#define PyUnicodeUCS2_EncodeASCII ((PyObject*(*)(const Py_UNICODE *data, Py_ssize_t length, const char *errors))imports[118].proc)
#define PyUnicodeUCS2_DecodeCharmap ((PyObject*(*)(const char *string, Py_ssize_t length, PyObject *mapping, const char *errors))imports[119].proc)
#define PyUnicodeUCS2_AsCharmapString ((PyObject*(*)(PyObject *unicode, PyObject *mapping))imports[120].proc)
#define PyUnicodeUCS2_EncodeCharmap ((PyObject*(*)(const Py_UNICODE *data, Py_ssize_t length, PyObject *mapping, const char *errors))imports[121].proc)
#define PyUnicodeUCS2_TranslateCharmap ((PyObject*(*)(const Py_UNICODE *data, Py_ssize_t length, PyObject *table, const char *errors))imports[122].proc)
#define PyUnicode_DecodeMBCS ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors))imports[123].proc)
#define PyUnicode_DecodeMBCSStateful ((PyObject*(*)(const char *string, Py_ssize_t length, const char *errors, Py_ssize_t *consumed))imports[124].proc)
#define PyUnicode_AsMBCSString ((PyObject*(*)(PyObject *unicode))imports[125].proc)
#define PyUnicode_EncodeMBCS ((PyObject*(*)(const Py_UNICODE *data, Py_ssize_t length, const char *errors))imports[126].proc)
#define PyUnicodeUCS2_EncodeDecimal ((int(*)(Py_UNICODE *s, Py_ssize_t length, char *output, const char *errors))imports[127].proc)
#define PyUnicodeUCS2_Concat ((PyObject*(*)(PyObject *left, PyObject *right))imports[128].proc)
#define PyUnicodeUCS2_Split ((PyObject*(*)(PyObject *s, PyObject *sep, Py_ssize_t maxsplit))imports[129].proc)
#define PyUnicodeUCS2_Splitlines ((PyObject*(*)(PyObject *s, int keepends))imports[130].proc)
#define PyUnicodeUCS2_Partition ((PyObject*(*)(PyObject *s, PyObject *sep))imports[131].proc)
#define PyUnicodeUCS2_RPartition ((PyObject*(*)(PyObject *s, PyObject *sep))imports[132].proc)
#define PyUnicodeUCS2_RSplit ((PyObject*(*)(PyObject *s, PyObject *sep, Py_ssize_t maxsplit))imports[133].proc)
#define PyUnicodeUCS2_Translate ((PyObject*(*)(PyObject *str, PyObject *table, const char *errors))imports[134].proc)
#define PyUnicodeUCS2_Join ((PyObject*(*)(PyObject *separator, PyObject *seq))imports[135].proc)
#define PyUnicodeUCS2_Tailmatch ((Py_ssize_t(*)(PyObject *str, PyObject *substr, Py_ssize_t start, Py_ssize_t end, int direction))imports[136].proc)
#define PyUnicodeUCS2_Find ((Py_ssize_t(*)(PyObject *str, PyObject *substr, Py_ssize_t start, Py_ssize_t end, int direction))imports[137].proc)
#define PyUnicodeUCS2_Count ((Py_ssize_t(*)(PyObject *str, PyObject *substr, Py_ssize_t start, Py_ssize_t end))imports[138].proc)
#define PyUnicodeUCS2_Replace ((PyObject*(*)(PyObject *str, PyObject *substr, PyObject *replstr, Py_ssize_t maxcount))imports[139].proc)
#define PyUnicodeUCS2_Compare ((int(*)(PyObject *left, PyObject *right))imports[140].proc)
#define PyUnicodeUCS2_RichCompare ((PyObject*(*)(PyObject *left, PyObject *right, int op))imports[141].proc)
#define PyUnicodeUCS2_Format ((PyObject*(*)(PyObject *format, PyObject *args))imports[142].proc)
#define PyUnicodeUCS2_Contains ((int(*)(PyObject *container, PyObject *element))imports[143].proc)
#define _PyUnicode_XStrip ((PyObject*(*)(PyUnicodeObject *self, int striptype, PyObject *sepobj))imports[144].proc)
#define _PyUnicodeUCS2_IsLowercase ((int(*)(Py_UNICODE ch))imports[145].proc)
#define _PyUnicodeUCS2_IsUppercase ((int(*)(Py_UNICODE ch))imports[146].proc)
#define _PyUnicodeUCS2_IsTitlecase ((int(*)(Py_UNICODE ch))imports[147].proc)
#define _PyUnicodeUCS2_IsWhitespace ((int(*)(const Py_UNICODE ch))imports[148].proc)
#define _PyUnicodeUCS2_IsLinebreak ((int(*)(const Py_UNICODE ch))imports[149].proc)
#define Py_UNICODE_PyUnicodeUCS2_ToLowercase ((int(*)(Py_UNICODE ch))imports[150].proc)
#define Py_UNICODE_PyUnicodeUCS2_ToUppercase ((int(*)(Py_UNICODE ch))imports[151].proc)
#define Py_UNICODE_PyUnicodeUCS2_ToTitlecase ((int(*)(Py_UNICODE ch))imports[152].proc)
#define _PyUnicodeUCS2_ToDecimalDigit ((int(*)(Py_UNICODE ch))imports[153].proc)
#define _PyUnicodeUCS2_ToDigit ((int(*)(Py_UNICODE ch))imports[154].proc)
#define _PyUnicodeUCS2_ToNumeric ((double(*)(Py_UNICODE ch))imports[155].proc)
#define _PyUnicodeUCS2_IsDecimalDigit ((int(*)(Py_UNICODE ch))imports[156].proc)
#define _PyUnicodeUCS2_IsDigit ((int(*)(Py_UNICODE ch))imports[157].proc)
#define _PyUnicodeUCS2_IsNumeric ((int(*)(Py_UNICODE ch))imports[158].proc)
#define _PyUnicodeUCS2_IsAlpha ((int(*)(Py_UNICODE ch))imports[159].proc)
#define PyInt_FromString ((PyObject*(*)(char *, char **, int))imports[160].proc)
#define PyInt_FromUnicode ((PyObject*(*)(Py_UNICODE *, Py_ssize_t, int))imports[161].proc)
#define PyInt_FromLong ((PyObject*(*)(long))imports[162].proc)
#define PyInt_FromSize_t ((PyObject*(*)(size_t))imports[163].proc)
#define PyInt_FromSsize_t ((PyObject*(*)(Py_ssize_t))imports[164].proc)
#define PyInt_AsLong ((long(*)(PyObject *))imports[165].proc)
#define PyInt_AsSsize_t ((Py_ssize_t(*)(PyObject *))imports[166].proc)
#define PyInt_AsUnsignedLongMask ((unsigned long(*)(PyObject *))imports[167].proc)
#define PyInt_AsUnsignedLongLongMask ((unsigned __int64(*)(PyObject *))imports[168].proc)
#define PyInt_GetMax ((long(*)(void))imports[169].proc)
#define PyOS_strtoul ((unsigned long(*)(char *, char **, int))imports[170].proc)
#define PyOS_strtol ((long(*)(char *, char **, int))imports[171].proc)
#define PyInt_ClearFreeList ((int(*)(void))imports[172].proc)
#define _PyInt_Format ((PyObject*(*)(PyIntObject *v, int base, int newstyle))imports[173].proc)
#define _PyInt_FormatAdvanced ((PyObject*(*)(PyObject *obj, char *format_spec, Py_ssize_t format_spec_len))imports[174].proc)
#define PyBool_FromLong ((PyObject*(*)(long))imports[175].proc)
#define PyLong_FromLong ((PyObject*(*)(long))imports[176].proc)
#define PyLong_FromUnsignedLong ((PyObject*(*)(unsigned long))imports[177].proc)
#define PyLong_FromDouble ((PyObject*(*)(double))imports[178].proc)
#define PyLong_FromSize_t ((PyObject*(*)(size_t))imports[179].proc)
#define PyLong_FromSsize_t ((PyObject*(*)(Py_ssize_t))imports[180].proc)
#define PyLong_AsLong ((long(*)(PyObject *))imports[181].proc)
#define PyLong_AsLongAndOverflow ((long(*)(PyObject *, int *))imports[182].proc)
#define PyLong_AsUnsignedLong ((unsigned long(*)(PyObject *))imports[183].proc)
#define PyLong_AsUnsignedLongMask ((unsigned long(*)(PyObject *))imports[184].proc)
#define PyLong_AsSsize_t ((Py_ssize_t(*)(PyObject *))imports[185].proc)
#define PyLong_GetInfo ((PyObject*(*)(void))imports[186].proc)
#define _PyLong_Frexp ((double(*)(PyLongObject *a, Py_ssize_t *e))imports[187].proc)
#define PyLong_AsDouble ((double(*)(PyObject *))imports[188].proc)
#define PyLong_FromPtr ((PyObject*(*)(void *))imports[189].proc)
#define PyLong_AsPtr ((void*(*)(PyObject *))imports[190].proc)
#define PyLong_FromLongLong ((PyObject*(*)(__int64))imports[191].proc)
#define PyLong_FromUnsignedLongLong ((PyObject*(*)(unsigned __int64))imports[192].proc)
#define PyLong_AsLongLong ((__int64(*)(PyObject *))imports[193].proc)
#define PyLong_AsUnsignedLongLong ((unsigned __int64(*)(PyObject *))imports[194].proc)
#define PyLong_AsUnsignedLongLongMask ((unsigned __int64(*)(PyObject *))imports[195].proc)
#define PyLong_AsLongLongAndOverflow ((__int64(*)(PyObject *, int *))imports[196].proc)
#define PyLong_FromString ((PyObject*(*)(char *, char **, int))imports[197].proc)
#define PyLong_FromUnicode ((PyObject*(*)(Py_UNICODE *, Py_ssize_t, int))imports[198].proc)
#define _PyLong_Sign ((int(*)(PyObject *v))imports[199].proc)
#define _PyLong_NumBits ((size_t(*)(PyObject *v))imports[200].proc)
#define _PyLong_FromByteArray ((PyObject*(*)(const unsigned char *bytes, size_t n, int little_endian, int is_signed))imports[201].proc)
#define _PyLong_AsByteArray ((int(*)(PyLongObject *v, unsigned char *bytes, size_t n, int little_endian, int is_signed))imports[202].proc)
#define _PyLong_Format ((PyObject*(*)(PyObject *aa, int base, int addL, int newstyle))imports[203].proc)
#define _PyLong_FormatAdvanced ((PyObject*(*)(PyObject *obj, char *format_spec, Py_ssize_t format_spec_len))imports[204].proc)
#define PyFloat_GetMax ((double(*)(void))imports[205].proc)
#define PyFloat_GetMin ((double(*)(void))imports[206].proc)
#define PyFloat_GetInfo ((PyObject*(*)(void))imports[207].proc)
#define PyFloat_FromString ((PyObject*(*)(PyObject *, char **junk))imports[208].proc)
#define PyFloat_FromDouble ((PyObject*(*)(double))imports[209].proc)
#define PyFloat_AsDouble ((double(*)(PyObject *))imports[210].proc)
#define PyFloat_AsReprString ((void(*)(char *, PyFloatObject *v))imports[211].proc)
#define PyFloat_AsString ((void(*)(char *, PyFloatObject *v))imports[212].proc)
#define _PyFloat_Pack4 ((int(*)(double x, unsigned char *p, int le))imports[213].proc)
#define _PyFloat_Pack8 ((int(*)(double x, unsigned char *p, int le))imports[214].proc)
#define _PyFloat_Digits ((int(*)(char *buf, double v, int *signum))imports[215].proc)
#define _PyFloat_DigitsInit ((void(*)(void))imports[216].proc)
#define _PyFloat_Unpack4 ((double(*)(const unsigned char *p, int le))imports[217].proc)
#define _PyFloat_Unpack8 ((double(*)(const unsigned char *p, int le))imports[218].proc)
#define PyFloat_ClearFreeList ((int(*)(void))imports[219].proc)
#define _PyFloat_FormatAdvanced ((PyObject*(*)(PyObject *obj, char *format_spec, Py_ssize_t format_spec_len))imports[220].proc)
#define _Py_double_round ((PyObject*(*)(double x, int ndigits))imports[221].proc)
#define Py_complex_Py_c_sum ((int(*)(Py_complex, Py_complex))imports[222].proc)
#define Py_complex_Py_c_diff ((int(*)(Py_complex, Py_complex))imports[223].proc)
#define Py_complex_Py_c_neg ((int(*)(Py_complex))imports[224].proc)
#define Py_complex_Py_c_prod ((int(*)(Py_complex, Py_complex))imports[225].proc)
#define Py_complex_Py_c_quot ((int(*)(Py_complex, Py_complex))imports[226].proc)
#define Py_complex_Py_c_pow ((int(*)(Py_complex, Py_complex))imports[227].proc)
#define _Py_c_abs ((double(*)(Py_complex))imports[228].proc)
#define PyComplex_FromCComplex ((PyObject*(*)(Py_complex))imports[229].proc)
#define PyComplex_FromDoubles ((PyObject*(*)(double real, double imag))imports[230].proc)
#define PyComplex_RealAsDouble ((double(*)(PyObject *op))imports[231].proc)
#define PyComplex_ImagAsDouble ((double(*)(PyObject *op))imports[232].proc)
#define Py_complexPyComplex_AsCComplex ((int(*)(PyObject *op))imports[233].proc)
#define _PyComplex_FormatAdvanced ((PyObject*(*)(PyObject *obj, char *format_spec, Py_ssize_t format_spec_len))imports[234].proc)
#define PyString_FromStringAndSize ((PyObject*(*)(const char *, Py_ssize_t))imports[235].proc)
#define PyString_FromString ((PyObject*(*)(const char *))imports[236].proc)
#define PyString_FromFormatV ((PyObject*(*)(const char *, va_list))imports[237].proc)
#define PyString_FromFormat ((PyObject*(*)(const char *, ...))imports[238].proc)
#define PyString_Size ((Py_ssize_t(*)(PyObject *))imports[239].proc)
#define PyString_AsString ((char*(*)(PyObject *))imports[240].proc)
#define PyString_Repr ((PyObject*(*)(PyObject *, int))imports[241].proc)
#define PyString_Concat ((void(*)(PyObject **, PyObject *))imports[242].proc)
#define PyString_ConcatAndDel ((void(*)(PyObject **, PyObject *))imports[243].proc)
#define _PyString_Resize ((int(*)(PyObject **, Py_ssize_t))imports[244].proc)
#define _PyString_Eq ((int(*)(PyObject *, PyObject *))imports[245].proc)
#define PyString_Format ((PyObject*(*)(PyObject *, PyObject *))imports[246].proc)
#define _PyString_FormatLong ((PyObject*(*)(PyObject *, int, int, int, char **, int *))imports[247].proc)
#define PyString_DecodeEscape ((PyObject*(*)(const char *, Py_ssize_t, const char *, Py_ssize_t, const char *))imports[248].proc)
#define PyString_InternInPlace ((void(*)(PyObject **))imports[249].proc)
#define PyString_InternImmortal ((void(*)(PyObject **))imports[250].proc)
#define PyString_InternFromString ((PyObject*(*)(const char *))imports[251].proc)
#define _Py_ReleaseInternedStrings ((void(*)(void))imports[252].proc)
#define _PyString_Join ((PyObject*(*)(PyObject *sep, PyObject *x))imports[253].proc)
#define PyString_Decode ((PyObject*(*)(const char *s, Py_ssize_t size, const char *encoding, const char *errors))imports[254].proc)
#define PyString_Encode ((PyObject*(*)(const char *s, Py_ssize_t size, const char *encoding, const char *errors))imports[255].proc)
#define PyString_AsEncodedObject ((PyObject*(*)(PyObject *str, const char *encoding, const char *errors))imports[256].proc)
#define PyString_AsEncodedString ((PyObject*(*)(PyObject *str, const char *encoding, const char *errors))imports[257].proc)
#define PyString_AsDecodedObject ((PyObject*(*)(PyObject *str, const char *encoding, const char *errors))imports[258].proc)
#define PyString_AsDecodedString ((PyObject*(*)(PyObject *str, const char *encoding, const char *errors))imports[259].proc)
#define PyString_AsStringAndSize ((int(*)(register PyObject *obj, register char **s, register Py_ssize_t *len))imports[260].proc)
#define _PyString_InsertThousandsGroupingLocale ((Py_ssize_t(*)(char *buffer, Py_ssize_t n_buffer, char *digits, Py_ssize_t n_digits, Py_ssize_t min_width))imports[261].proc)
#define _PyString_InsertThousandsGrouping ((Py_ssize_t(*)(char *buffer, Py_ssize_t n_buffer, char *digits, Py_ssize_t n_digits, Py_ssize_t min_width, const char *grouping, const char *thousands_sep))imports[262].proc)
#define _PyBytes_FormatAdvanced ((PyObject*(*)(PyObject *obj, char *format_spec, Py_ssize_t format_spec_len))imports[263].proc)
#define PyMemoryView_GetContiguous ((PyObject*(*)(PyObject *base, int buffertype, char fort))imports[264].proc)
#define PyMemoryView_FromObject ((PyObject*(*)(PyObject *base))imports[265].proc)
#define PyMemoryView_FromBuffer ((PyObject*(*)(Py_buffer *info))imports[266].proc)
#define PyBuffer_FromObject ((PyObject*(*)(PyObject *base, Py_ssize_t offset, Py_ssize_t size))imports[267].proc)
#define PyBuffer_FromReadWriteObject ((PyObject*(*)(PyObject *base, Py_ssize_t offset, Py_ssize_t size))imports[268].proc)
#define PyBuffer_FromMemory ((PyObject*(*)(void *ptr, Py_ssize_t size))imports[269].proc)
#define PyBuffer_FromReadWriteMemory ((PyObject*(*)(void *ptr, Py_ssize_t size))imports[270].proc)
#define PyBuffer_New ((PyObject*(*)(Py_ssize_t size))imports[271].proc)
#define PyByteArray_FromObject ((PyObject*(*)(PyObject *))imports[272].proc)
#define PyByteArray_Concat ((PyObject*(*)(PyObject *, PyObject *))imports[273].proc)
#define PyByteArray_FromStringAndSize ((PyObject*(*)(const char *, Py_ssize_t))imports[274].proc)
#define PyByteArray_Size ((Py_ssize_t(*)(PyObject *))imports[275].proc)
#define PyByteArray_AsString ((char*(*)(PyObject *))imports[276].proc)
#define PyByteArray_Resize ((int(*)(PyObject *, Py_ssize_t))imports[277].proc)
#define PyTuple_New ((PyObject*(*)(Py_ssize_t size))imports[278].proc)
#define PyTuple_Size ((Py_ssize_t(*)(PyObject *))imports[279].proc)
#define PyTuple_GetItem ((PyObject*(*)(PyObject *, Py_ssize_t))imports[280].proc)
#define PyTuple_SetItem ((int(*)(PyObject *, Py_ssize_t, PyObject *))imports[281].proc)
#define PyTuple_GetSlice ((PyObject*(*)(PyObject *, Py_ssize_t, Py_ssize_t))imports[282].proc)
#define _PyTuple_Resize ((int(*)(PyObject **, Py_ssize_t))imports[283].proc)
#define PyTuple_Pack ((PyObject*(*)(Py_ssize_t, ...))imports[284].proc)
#define _PyTuple_MaybeUntrack ((void(*)(PyObject *))imports[285].proc)
#define PyTuple_ClearFreeList ((int(*)(void))imports[286].proc)
#define PyList_New ((PyObject*(*)(Py_ssize_t size))imports[287].proc)
#define PyList_Size ((Py_ssize_t(*)(PyObject *))imports[288].proc)
#define PyList_GetItem ((PyObject*(*)(PyObject *, Py_ssize_t))imports[289].proc)
#define PyList_SetItem ((int(*)(PyObject *, Py_ssize_t, PyObject *))imports[290].proc)
#define PyList_Insert ((int(*)(PyObject *, Py_ssize_t, PyObject *))imports[291].proc)
#define PyList_Append ((int(*)(PyObject *, PyObject *))imports[292].proc)
#define PyList_GetSlice ((PyObject*(*)(PyObject *, Py_ssize_t, Py_ssize_t))imports[293].proc)
#define PyList_SetSlice ((int(*)(PyObject *, Py_ssize_t, Py_ssize_t, PyObject *))imports[294].proc)
#define PyList_Sort ((int(*)(PyObject *))imports[295].proc)
#define PyList_Reverse ((int(*)(PyObject *))imports[296].proc)
#define PyList_AsTuple ((PyObject*(*)(PyObject *))imports[297].proc)
#define _PyList_Extend ((PyObject*(*)(PyListObject *, PyObject *))imports[298].proc)
#define PyDict_New ((PyObject*(*)(void))imports[299].proc)
#define PyDict_GetItem ((PyObject*(*)(PyObject *mp, PyObject *key))imports[300].proc)
#define PyDict_SetItem ((int(*)(PyObject *mp, PyObject *key, PyObject *item))imports[301].proc)
#define PyDict_DelItem ((int(*)(PyObject *mp, PyObject *key))imports[302].proc)
#define PyDict_Clear ((void(*)(PyObject *mp))imports[303].proc)
#define PyDict_Next ((int(*)(PyObject *mp, Py_ssize_t *pos, PyObject **key, PyObject **value))imports[304].proc)
#define _PyDict_Next ((int(*)(PyObject *mp, Py_ssize_t *pos, PyObject **key, PyObject **value, long *hash))imports[305].proc)
#define PyDict_Keys ((PyObject*(*)(PyObject *mp))imports[306].proc)
#define PyDict_Values ((PyObject*(*)(PyObject *mp))imports[307].proc)
#define PyDict_Items ((PyObject*(*)(PyObject *mp))imports[308].proc)
#define PyDict_Size ((Py_ssize_t(*)(PyObject *mp))imports[309].proc)
#define PyDict_Copy ((PyObject*(*)(PyObject *mp))imports[310].proc)
#define PyDict_Contains ((int(*)(PyObject *mp, PyObject *key))imports[311].proc)
#define _PyDict_Contains ((int(*)(PyObject *mp, PyObject *key, long hash))imports[312].proc)
#define _PyDict_NewPresized ((PyObject*(*)(Py_ssize_t minused))imports[313].proc)
#define _PyDict_MaybeUntrack ((void(*)(PyObject *mp))imports[314].proc)
#define PyDict_Update ((int(*)(PyObject *mp, PyObject *other))imports[315].proc)
#define PyDict_Merge ((int(*)(PyObject *mp, PyObject *other, int override))imports[316].proc)
#define PyDict_MergeFromSeq2 ((int(*)(PyObject *d, PyObject *seq2, int override))imports[317].proc)
#define PyDict_GetItemString ((PyObject*(*)(PyObject *dp, const char *key))imports[318].proc)
#define PyDict_SetItemString ((int(*)(PyObject *dp, const char *key, PyObject *item))imports[319].proc)
#define PyDict_DelItemString ((int(*)(PyObject *dp, const char *key))imports[320].proc)
#define PySet_New ((PyObject*(*)(PyObject *))imports[321].proc)
#define PyFrozenSet_New ((PyObject*(*)(PyObject *))imports[322].proc)
#define PySet_Size ((Py_ssize_t(*)(PyObject *anyset))imports[323].proc)
#define PySet_Clear ((int(*)(PyObject *set))imports[324].proc)
#define PySet_Contains ((int(*)(PyObject *anyset, PyObject *key))imports[325].proc)
#define PySet_Discard ((int(*)(PyObject *set, PyObject *key))imports[326].proc)
#define PySet_Add ((int(*)(PyObject *set, PyObject *key))imports[327].proc)
#define _PySet_Next ((int(*)(PyObject *set, Py_ssize_t *pos, PyObject **key))imports[328].proc)
#define _PySet_NextEntry ((int(*)(PyObject *set, Py_ssize_t *pos, PyObject **key, long *hash))imports[329].proc)
#define PySet_Pop ((PyObject*(*)(PyObject *set))imports[330].proc)
#define _PySet_Update ((int(*)(PyObject *set, PyObject *iterable))imports[331].proc)
#define PyCFunctionPyCFunction_GetFunction ((int(*)(PyObject *))imports[332].proc)
#define PyCFunction_GetSelf ((PyObject*(*)(PyObject *))imports[333].proc)
#define PyCFunction_GetFlags ((int(*)(PyObject *))imports[334].proc)
#define PyCFunction_Call ((PyObject*(*)(PyObject *, PyObject *, PyObject *))imports[335].proc)
#define Py_FindMethod ((PyObject*(*)(PyMethodDef [], PyObject *, const char *))imports[336].proc)
#define PyCFunction_NewEx ((PyObject*(*)(PyMethodDef *, PyObject *, PyObject *))imports[337].proc)
#define Py_FindMethodInChain ((PyObject*(*)(PyMethodChain *, PyObject *, const char *))imports[338].proc)
#define PyCFunction_ClearFreeList ((int(*)(void))imports[339].proc)
#define PyModule_New ((PyObject*(*)(const char *))imports[340].proc)
#define PyModule_GetDict ((PyObject*(*)(PyObject *))imports[341].proc)
#define PyModule_GetName ((char*(*)(PyObject *))imports[342].proc)
#define PyModule_GetFilename ((char*(*)(PyObject *))imports[343].proc)
#define _PyModule_Clear ((void(*)(PyObject *))imports[344].proc)
#define PyFunction_New ((PyObject*(*)(PyObject *, PyObject *))imports[345].proc)
#define PyFunction_GetCode ((PyObject*(*)(PyObject *))imports[346].proc)
#define PyFunction_GetGlobals ((PyObject*(*)(PyObject *))imports[347].proc)
#define PyFunction_GetModule ((PyObject*(*)(PyObject *))imports[348].proc)
#define PyFunction_GetDefaults ((PyObject*(*)(PyObject *))imports[349].proc)
#define PyFunction_SetDefaults ((int(*)(PyObject *, PyObject *))imports[350].proc)
#define PyFunction_GetClosure ((PyObject*(*)(PyObject *))imports[351].proc)
#define PyFunction_SetClosure ((int(*)(PyObject *, PyObject *))imports[352].proc)
#define PyClassMethod_New ((PyObject*(*)(PyObject *))imports[353].proc)
#define PyStaticMethod_New ((PyObject*(*)(PyObject *))imports[354].proc)
#define PyClass_New ((PyObject*(*)(PyObject *, PyObject *, PyObject *))imports[355].proc)
#define PyInstance_New ((PyObject*(*)(PyObject *, PyObject *, PyObject *))imports[356].proc)
#define PyInstance_NewRaw ((PyObject*(*)(PyObject *, PyObject *))imports[357].proc)
#define PyMethod_New ((PyObject*(*)(PyObject *, PyObject *, PyObject *))imports[358].proc)
#define PyMethod_Function ((PyObject*(*)(PyObject *))imports[359].proc)
#define PyMethod_Self ((PyObject*(*)(PyObject *))imports[360].proc)
#define PyMethod_Class ((PyObject*(*)(PyObject *))imports[361].proc)
#define _PyInstance_Lookup ((PyObject*(*)(PyObject *pinst, PyObject *name))imports[362].proc)
#define PyClass_IsSubclass ((int(*)(PyObject *, PyObject *))imports[363].proc)
#define PyMethod_ClearFreeList ((int(*)(void))imports[364].proc)
#define PyFile_FromString ((PyObject*(*)(char *, char *))imports[365].proc)
#define PyFile_SetBufSize ((void(*)(PyObject *, int))imports[366].proc)
#define PyFile_SetEncoding ((int(*)(PyObject *, const char *))imports[367].proc)
#define PyFile_SetEncodingAndErrors ((int(*)(PyObject *, const char *, char *errors))imports[368].proc)
#define PyFile_FromFile ((PyObject*(*)(FILE *fp, char *name, char *mode, int (*close)(FILE *)))imports[369].proc)
#define PyFile_AsFile ((FILE*(*)(PyObject *))imports[370].proc)
#define PyFile_IncUseCount ((void(*)(PyFileObject *))imports[371].proc)
#define PyFile_DecUseCount ((void(*)(PyFileObject *))imports[372].proc)
#define PyFile_Name ((PyObject*(*)(PyObject *))imports[373].proc)
#define PyFile_GetLine ((PyObject*(*)(PyObject *, int))imports[374].proc)
#define PyFile_WriteObject ((int(*)(PyObject *, PyObject *, int))imports[375].proc)
#define PyFile_SoftSpace ((int(*)(PyObject *, int))imports[376].proc)
#define PyFile_WriteString ((int(*)(const char *, PyObject *))imports[377].proc)
#define PyObject_AsFileDescriptor ((int(*)(PyObject *))imports[378].proc)
#define Py_UniversalNewlineFgets ((char*(*)(char *, int, FILE *, PyObject *))imports[379].proc)
#define Py_UniversalNewlineFread ((size_t(*)(char *, size_t, FILE *, PyObject *))imports[380].proc)
#define _PyFile_SanitizeMode ((int(*)(char *mode))imports[381].proc)
#define PyCObject_FromPtr ((PyObject*(*)(void *cobj, void (*destr)(void *)))imports[382].proc)
#define PyCObject_FromVoidPtrAndDesc ((PyObject*(*)(void *cobj, void *desc, void (*destr)(void *, void *)))imports[383].proc)
#define PyCObject_AsPtr ((void*(*)(PyObject *))imports[384].proc)
#define PyCObject_GetDesc ((void*(*)(PyObject *))imports[385].proc)
#define PyCObject_Import ((void*(*)(char *module_name, char *cobject_name))imports[386].proc)
#define PyCObject_SetPtr ((int(*)(PyObject *self, void *cobj))imports[387].proc)
#define PyCapsule_New ((PyObject*(*)(void *pointer, const char *name, PyCapsule_Destructor destructor))imports[388].proc)
#define PyCapsule_GetPointer ((void*(*)(PyObject *capsule, const char *name))imports[389].proc)
#define PyCapsule_DestructorPyCapsule_GetDestructor ((int(*)(PyObject *capsule))imports[390].proc)
#define PyCapsule_GetName ((const char*(*)(PyObject *capsule))imports[391].proc)
#define PyCapsule_GetContext ((void*(*)(PyObject *capsule))imports[392].proc)
#define PyCapsule_IsValid ((int(*)(PyObject *capsule, const char *name))imports[393].proc)
#define PyCapsule_SetPointer ((int(*)(PyObject *capsule, void *pointer))imports[394].proc)
#define PyCapsule_SetDestructor ((int(*)(PyObject *capsule, PyCapsule_Destructor destructor))imports[395].proc)
#define PyCapsule_SetName ((int(*)(PyObject *capsule, const char *name))imports[396].proc)
#define PyCapsule_SetContext ((int(*)(PyObject *capsule, void *context))imports[397].proc)
#define PyCapsule_Import ((void*(*)(const char *name, int no_block))imports[398].proc)
#define PyTraceBack_Here ((int(*)(struct _frame *))imports[399].proc)
#define PyTraceBack_Print ((int(*)(PyObject *, PyObject *))imports[400].proc)
#define _Py_DisplaySourceLine ((int(*)(PyObject *, const char *, int, int))imports[401].proc)
#define PySlice_New ((PyObject*(*)(PyObject *start, PyObject *stop, PyObject *step))imports[402].proc)
#define _PySlice_FromIndices ((PyObject*(*)(Py_ssize_t start, Py_ssize_t stop))imports[403].proc)
#define PySlice_GetIndices ((int(*)(PySliceObject *r, Py_ssize_t length, Py_ssize_t *start, Py_ssize_t *stop, Py_ssize_t *step))imports[404].proc)
#define PySlice_GetIndicesEx ((int(*)(PySliceObject *r, Py_ssize_t length, Py_ssize_t *start, Py_ssize_t *stop, Py_ssize_t *step, Py_ssize_t *slicelength))imports[405].proc)
#define PyCell_New ((PyObject*(*)(PyObject *))imports[406].proc)
#define PyCell_Get ((PyObject*(*)(PyObject *))imports[407].proc)
#define PyCell_Set ((int(*)(PyObject *, PyObject *))imports[408].proc)
#define PySeqIter_New ((PyObject*(*)(PyObject *))imports[409].proc)
#define PyCallIter_New ((PyObject*(*)(PyObject *, PyObject *))imports[410].proc)
#define PyGen_New ((PyObject*(*)(struct _frame *))imports[411].proc)
#define PyGen_NeedsFinalizing ((int(*)(PyGenObject *))imports[412].proc)
#define PyDescr_NewMethod ((PyObject*(*)(PyTypeObject *, PyMethodDef *))imports[413].proc)
#define PyDescr_NewClassMethod ((PyObject*(*)(PyTypeObject *, PyMethodDef *))imports[414].proc)
#define PyDescr_NewMember ((PyObject*(*)(PyTypeObject *, struct PyMemberDef *))imports[415].proc)
#define PyDescr_NewGetSet ((PyObject*(*)(PyTypeObject *, struct PyGetSetDef *))imports[416].proc)
#define PyDescr_NewWrapper ((PyObject*(*)(PyTypeObject *, struct wrapperbase *, void *))imports[417].proc)
#define PyDictProxy_New ((PyObject*(*)(PyObject *))imports[418].proc)
#define PyWrapper_New ((PyObject*(*)(PyObject *, PyObject *))imports[419].proc)
#define _PyWarnings_Init ((void(*)(void))imports[420].proc)
#define PyErr_WarnEx ((int(*)(PyObject *, const char *, Py_ssize_t))imports[421].proc)
#define PyErr_WarnExplicit ((int(*)(PyObject *, const char *, const char *, int, const char *, PyObject *))imports[422].proc)
#define PyWeakref_NewRef ((PyObject*(*)(PyObject *ob, PyObject *callback))imports[423].proc)
#define PyWeakref_NewProxy ((PyObject*(*)(PyObject *ob, PyObject *callback))imports[424].proc)
#define PyWeakref_GetObject ((PyObject*(*)(PyObject *ref))imports[425].proc)
#define _PyWeakref_GetWeakrefCount ((Py_ssize_t(*)(PyWeakReference *head))imports[426].proc)
#define _PyWeakref_ClearRef ((void(*)(PyWeakReference *self))imports[427].proc)
#define PyCodec_Register ((int(*)(PyObject *search_function))imports[428].proc)
#define _PyCodec_Lookup ((PyObject*(*)(const char *encoding))imports[429].proc)
#define PyCodec_Encode ((PyObject*(*)(PyObject *object, const char *encoding, const char *errors))imports[430].proc)
#define PyCodec_Decode ((PyObject*(*)(PyObject *object, const char *encoding, const char *errors))imports[431].proc)
#define PyCodec_Encoder ((PyObject*(*)(const char *encoding))imports[432].proc)
#define PyCodec_Decoder ((PyObject*(*)(const char *encoding))imports[433].proc)
#define PyCodec_IncrementalEncoder ((PyObject*(*)(const char *encoding, const char *errors))imports[434].proc)
#define PyCodec_IncrementalDecoder ((PyObject*(*)(const char *encoding, const char *errors))imports[435].proc)
#define PyCodec_StreamReader ((PyObject*(*)(const char *encoding, PyObject *stream, const char *errors))imports[436].proc)
#define PyCodec_StreamWriter ((PyObject*(*)(const char *encoding, PyObject *stream, const char *errors))imports[437].proc)
#define PyCodec_RegisterError ((int(*)(const char *name, PyObject *error))imports[438].proc)
#define PyCodec_LookupError ((PyObject*(*)(const char *name))imports[439].proc)
#define PyCodec_StrictErrors ((PyObject*(*)(PyObject *exc))imports[440].proc)
#define PyCodec_IgnoreErrors ((PyObject*(*)(PyObject *exc))imports[441].proc)
#define PyCodec_ReplaceErrors ((PyObject*(*)(PyObject *exc))imports[442].proc)
#define PyCodec_XMLCharRefReplaceErrors ((PyObject*(*)(PyObject *exc))imports[443].proc)
#define PyCodec_BackslashReplaceErrors ((PyObject*(*)(PyObject *exc))imports[444].proc)
#define PyErr_SetNone ((void(*)(PyObject *))imports[445].proc)
#define PyErr_SetObject ((void(*)(PyObject *, PyObject *))imports[446].proc)
#define PyErr_SetString ((void(*)(PyObject *, const char *))imports[447].proc)
#define PyErr_Occurred ((PyObject*(*)(void))imports[448].proc)
#define PyErr_Clear ((void(*)(void))imports[449].proc)
#define PyErr_Fetch ((void(*)(PyObject **, PyObject **, PyObject **))imports[450].proc)
#define PyErr_Restore ((void(*)(PyObject *, PyObject *, PyObject *))imports[451].proc)
#define PyErr_GivenExceptionMatches ((int(*)(PyObject *, PyObject *))imports[452].proc)
#define PyErr_ExceptionMatches ((int(*)(PyObject *))imports[453].proc)
#define PyErr_NormalizeException ((void(*)(PyObject **, PyObject **, PyObject **))imports[454].proc)
#define PyErr_BadArgument ((int(*)(void))imports[455].proc)
#define PyErr_NoMemory ((PyObject*(*)(void))imports[456].proc)
#define PyErr_SetFromErrno ((PyObject*(*)(PyObject *))imports[457].proc)
#define PyErr_SetFromErrnoWithFilenameObject ((PyObject*(*)(PyObject *, PyObject *))imports[458].proc)
#define PyErr_SetFromErrnoWithFilename ((PyObject*(*)(PyObject *, const char *))imports[459].proc)
#define PyErr_SetFromErrnoWithUnicodeFilename ((PyObject*(*)(PyObject *, const Py_UNICODE *))imports[460].proc)
#define PyErr_Format ((PyObject*(*)(PyObject *, const char *, ...))imports[461].proc)
#define PyErr_SetFromWindowsErrWithFilenameObject ((PyObject*(*)(int, const char *))imports[462].proc)
#define PyErr_SetFromWindowsErrWithFilename ((PyObject*(*)(int, const char *))imports[463].proc)
#define PyErr_SetFromWindowsErrWithUnicodeFilename ((PyObject*(*)(int, const Py_UNICODE *))imports[464].proc)
#define PyErr_SetFromWindowsErr ((PyObject*(*)(int))imports[465].proc)
#define PyErr_SetExcFromWindowsErrWithFilenameObject ((PyObject*(*)(PyObject *, int, PyObject *))imports[466].proc)
#define PyErr_SetExcFromWindowsErrWithFilename ((PyObject*(*)(PyObject *, int, const char *))imports[467].proc)
#define PyErr_SetExcFromWindowsErrWithUnicodeFilename ((PyObject*(*)(PyObject *, int, const Py_UNICODE *))imports[468].proc)
#define PyErr_SetExcFromWindowsErr ((PyObject*(*)(PyObject *, int))imports[469].proc)
#define PyErr_BadInternalCall ((void(*)(void))imports[470].proc)
#define _PyErr_BadInternalCall ((void(*)(char *filename, int lineno))imports[471].proc)
#define PyErr_NewException ((PyObject*(*)(char *name, PyObject *base, PyObject *dict))imports[472].proc)
#define PyErr_NewExceptionWithDoc ((PyObject*(*)(char *name, char *doc, PyObject *base, PyObject *dict))imports[473].proc)
#define PyErr_WriteUnraisable ((void(*)(PyObject *))imports[474].proc)
#define PyErr_CheckSignals ((int(*)(void))imports[475].proc)
#define PyErr_SetInterrupt ((void(*)(void))imports[476].proc)
#define PySignal_SetWakeupFd ((int(*)(int fd))imports[477].proc)
#define PyErr_SyntaxLocation ((void(*)(const char *, int))imports[478].proc)
#define PyErr_ProgramText ((PyObject*(*)(const char *, int))imports[479].proc)
#define PyUnicodeDecodeError_Create ((PyObject*(*)(const char *, const char *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *))imports[480].proc)
#define PyUnicodeEncodeError_Create ((PyObject*(*)(const char *, const Py_UNICODE *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *))imports[481].proc)
#define PyUnicodeTranslateError_Create ((PyObject*(*)(const Py_UNICODE *, Py_ssize_t, Py_ssize_t, Py_ssize_t, const char *))imports[482].proc)
#define PyUnicodeEncodeError_GetEncoding ((PyObject*(*)(PyObject *))imports[483].proc)
#define PyUnicodeDecodeError_GetEncoding ((PyObject*(*)(PyObject *))imports[484].proc)
#define PyUnicodeEncodeError_GetObject ((PyObject*(*)(PyObject *))imports[485].proc)
#define PyUnicodeDecodeError_GetObject ((PyObject*(*)(PyObject *))imports[486].proc)
#define PyUnicodeTranslateError_GetObject ((PyObject*(*)(PyObject *))imports[487].proc)
#define PyUnicodeEncodeError_GetStart ((int(*)(PyObject *, Py_ssize_t *))imports[488].proc)
#define PyUnicodeDecodeError_GetStart ((int(*)(PyObject *, Py_ssize_t *))imports[489].proc)
#define PyUnicodeTranslateError_GetStart ((int(*)(PyObject *, Py_ssize_t *))imports[490].proc)
#define PyUnicodeEncodeError_SetStart ((int(*)(PyObject *, Py_ssize_t))imports[491].proc)
#define PyUnicodeDecodeError_SetStart ((int(*)(PyObject *, Py_ssize_t))imports[492].proc)
#define PyUnicodeTranslateError_SetStart ((int(*)(PyObject *, Py_ssize_t))imports[493].proc)
#define PyUnicodeEncodeError_GetEnd ((int(*)(PyObject *, Py_ssize_t *))imports[494].proc)
#define PyUnicodeDecodeError_GetEnd ((int(*)(PyObject *, Py_ssize_t *))imports[495].proc)
#define PyUnicodeTranslateError_GetEnd ((int(*)(PyObject *, Py_ssize_t *))imports[496].proc)
#define PyUnicodeEncodeError_SetEnd ((int(*)(PyObject *, Py_ssize_t))imports[497].proc)
#define PyUnicodeDecodeError_SetEnd ((int(*)(PyObject *, Py_ssize_t))imports[498].proc)
#define PyUnicodeTranslateError_SetEnd ((int(*)(PyObject *, Py_ssize_t))imports[499].proc)
#define PyUnicodeEncodeError_GetReason ((PyObject*(*)(PyObject *))imports[500].proc)
#define PyUnicodeDecodeError_GetReason ((PyObject*(*)(PyObject *))imports[501].proc)
#define PyUnicodeTranslateError_GetReason ((PyObject*(*)(PyObject *))imports[502].proc)
#define PyUnicodeEncodeError_SetReason ((int(*)(PyObject *, const char *))imports[503].proc)
#define PyUnicodeDecodeError_SetReason ((int(*)(PyObject *, const char *))imports[504].proc)
#define PyUnicodeTranslateError_SetReason ((int(*)(PyObject *, const char *))imports[505].proc)
#define PyOS_snprintf ((int(*)(char *str, size_t size, const char *format, ...))imports[506].proc)
#define PyOS_vsnprintf ((int(*)(char *str, size_t size, const char *format, va_list va))imports[507].proc)
#define PyInterpreterState_New ((PyInterpreterState*(*)(void))imports[508].proc)
#define PyInterpreterState_Clear ((void(*)(PyInterpreterState *))imports[509].proc)
#define PyInterpreterState_Delete ((void(*)(PyInterpreterState *))imports[510].proc)
#define PyThreadState_New ((PyThreadState*(*)(PyInterpreterState *))imports[511].proc)
#define _PyThreadState_Prealloc ((PyThreadState*(*)(PyInterpreterState *))imports[512].proc)
#define _PyThreadState_Init ((void(*)(PyThreadState *))imports[513].proc)
#define PyThreadState_Clear ((void(*)(PyThreadState *))imports[514].proc)
#define PyThreadState_Delete ((void(*)(PyThreadState *))imports[515].proc)
#define PyThreadState_DeleteCurrent ((void(*)(void))imports[516].proc)
#define _PyGILState_Reinit ((void(*)(void))imports[517].proc)
#define PyThreadState_Get ((PyThreadState*(*)(void))imports[518].proc)
#define PyThreadState_Swap ((PyThreadState*(*)(PyThreadState *))imports[519].proc)
#define PyThreadState_GetDict ((PyObject*(*)(void))imports[520].proc)
#define PyThreadState_SetAsyncExc ((int(*)(long, PyObject *))imports[521].proc)
#define PyGILState_STATEPyGILState_Ensure ((int(*)(void))imports[522].proc)
#define PyGILState_Release ((void(*)(PyGILState_STATE))imports[523].proc)
#define PyGILState_GetThisThreadState ((PyThreadState*(*)(void))imports[524].proc)
#define _PyThread_CurrentFrames ((PyObject*(*)(void))imports[525].proc)
#define PyInterpreterState_Head ((PyInterpreterState*(*)(void))imports[526].proc)
#define PyInterpreterState_Next ((PyInterpreterState*(*)(PyInterpreterState *))imports[527].proc)
#define PyInterpreterState_ThreadHead ((PyThreadState*(*)(PyInterpreterState *))imports[528].proc)
#define PyThreadState_Next ((PyThreadState*(*)(PyThreadState *))imports[529].proc)
#define PyArena_New ((PyArena*(*)(void))imports[530].proc)
#define PyArena_Free ((void(*)(PyArena *))imports[531].proc)
#define PyArena_Malloc ((void*(*)(PyArena *, size_t size))imports[532].proc)
#define PyArena_AddPyObject ((int(*)(PyArena *, PyObject *))imports[533].proc)
#define _Py_VaBuildValue_SizeT ((PyObject*(*)(const char *, va_list))imports[534].proc)
#define PyArg_Parse ((int(*)(PyObject *, const char *, ...))imports[535].proc)
#define PyArg_ParseTupleAndKeywords ((int(*)(PyObject *, PyObject *, const char *, char **, ...))imports[536].proc)
#define PyArg_UnpackTuple ((int(*)(PyObject *, const char *, Py_ssize_t, Py_ssize_t, ...))imports[537].proc)
#define Py_BuildValue ((PyObject*(*)(const char *, ...))imports[538].proc)
#define _Py_BuildValue_SizeT ((PyObject*(*)(const char *, ...))imports[539].proc)
#define _PyArg_NoKeywords ((int(*)(const char *funcname, PyObject *kw))imports[540].proc)
#define PyArg_VaParse ((int(*)(PyObject *, const char *, va_list))imports[541].proc)
#define PyArg_VaParseTupleAndKeywords ((int(*)(PyObject *, PyObject *, const char *, char **, va_list))imports[542].proc)
#define Py_VaBuildValue ((PyObject*(*)(const char *, va_list))imports[543].proc)
#define PyModule_AddObject ((int(*)(PyObject *, const char *, PyObject *))imports[544].proc)
#define PyModule_AddIntConstant ((int(*)(PyObject *, const char *, long))imports[545].proc)
#define PyModule_AddStringConstant ((int(*)(PyObject *, const char *, const char *))imports[546].proc)
#define Py_InitModule4 ((PyObject*(*)(const char *name, PyMethodDef *methods, const char *doc, PyObject *self, int apiver))imports[547].proc)
#define Py_SetProgramName ((void(*)(char *))imports[548].proc)
#define Py_GetProgramName ((char*(*)(void))imports[549].proc)
#define Py_SetPythonHome ((void(*)(char *))imports[550].proc)
#define Py_GetPythonHome ((char*(*)(void))imports[551].proc)
#define Py_Initialize ((void(*)(void))imports[552].proc)
#define Py_InitializeEx ((void(*)(int))imports[553].proc)
#define Py_Finalize ((void(*)(void))imports[554].proc)
#define Py_IsInitialized ((int(*)(void))imports[555].proc)
#define Py_NewInterpreter ((PyThreadState*(*)(void))imports[556].proc)
#define Py_EndInterpreter ((void(*)(PyThreadState *))imports[557].proc)
#define PyRun_AnyFileFlags ((int(*)(FILE *, const char *, PyCompilerFlags *))imports[558].proc)
#define PyRun_AnyFileExFlags ((int(*)(FILE *, const char *, int, PyCompilerFlags *))imports[559].proc)
#define PyRun_SimpleStringFlags ((int(*)(const char *, PyCompilerFlags *))imports[560].proc)
#define PyRun_SimpleFileExFlags ((int(*)(FILE *, const char *, int, PyCompilerFlags *))imports[561].proc)
#define PyRun_InteractiveOneFlags ((int(*)(FILE *, const char *, PyCompilerFlags *))imports[562].proc)
#define PyRun_InteractiveLoopFlags ((int(*)(FILE *, const char *, PyCompilerFlags *))imports[563].proc)
#define PyParser_ASTFromString ((struct _mod*(*)(const char *, const char *, int, PyCompilerFlags *flags, PyArena *))imports[564].proc)
#define PyParser_ASTFromFile ((struct _mod*(*)(FILE *, const char *, int, char *, char *, PyCompilerFlags *, int *, PyArena *))imports[565].proc)
#define PyParser_SimpleParseStringFlags ((struct _node*(*)(const char *, int, int))imports[566].proc)
#define PyParser_SimpleParseFileFlags ((struct _node*(*)(FILE *, const char *, int, int))imports[567].proc)
#define PyRun_StringFlags ((PyObject*(*)(const char *, int, PyObject *, PyObject *, PyCompilerFlags *))imports[568].proc)
#define PyRun_FileExFlags ((PyObject*(*)(FILE *, const char *, int, PyObject *, PyObject *, int, PyCompilerFlags *))imports[569].proc)
#define Py_CompileStringFlags ((PyObject*(*)(const char *, const char *, int, PyCompilerFlags *))imports[570].proc)
#define Py_SymtableString ((struct symtable*(*)(const char *, const char *, int))imports[571].proc)
#define PyErr_Print ((void(*)(void))imports[572].proc)
#define PyErr_PrintEx ((void(*)(int))imports[573].proc)
#define PyErr_Display ((void(*)(PyObject *, PyObject *, PyObject *))imports[574].proc)
#define Py_AtExit ((int(*)(void (*func)(void)))imports[575].proc)
#define Py_Exit ((void(*)(int))imports[576].proc)
#define Py_FdIsInteractive ((int(*)(FILE *, const char *))imports[577].proc)
#define Py_Main ((int(*)(int argc, char **argv))imports[578].proc)
#define Py_GetProgramFullPath ((char*(*)(void))imports[579].proc)
#define Py_GetPrefix ((char*(*)(void))imports[580].proc)
#define Py_GetExecPrefix ((char*(*)(void))imports[581].proc)
#define Py_GetPath ((char*(*)(void))imports[582].proc)
#define Py_GetVersion ((const char*(*)(void))imports[583].proc)
#define Py_GetPlatform ((const char*(*)(void))imports[584].proc)
#define Py_GetCopyright ((const char*(*)(void))imports[585].proc)
#define Py_GetCompiler ((const char*(*)(void))imports[586].proc)
#define Py_GetBuildInfo ((const char*(*)(void))imports[587].proc)
#define _Py_svnversion ((const char*(*)(void))imports[588].proc)
#define Py_SubversionRevision ((const char*(*)(void))imports[589].proc)
#define Py_SubversionShortBranch ((const char*(*)(void))imports[590].proc)
#define _Py_hgidentifier ((const char*(*)(void))imports[591].proc)
#define _Py_hgversion ((const char*(*)(void))imports[592].proc)
#define _PyBuiltin_Init ((PyObject*(*)(void))imports[593].proc)
#define _PySys_Init ((PyObject*(*)(void))imports[594].proc)
#define _PyImport_Init ((void(*)(void))imports[595].proc)
#define _PyExc_Init ((void(*)(void))imports[596].proc)
#define _PyImportHooks_Init ((void(*)(void))imports[597].proc)
#define _PyFrame_Init ((int(*)(void))imports[598].proc)
#define _PyInt_Init ((int(*)(void))imports[599].proc)
#define _PyLong_Init ((int(*)(void))imports[600].proc)
#define _PyFloat_Init ((void(*)(void))imports[601].proc)
#define PyByteArray_Init ((int(*)(void))imports[602].proc)
#define _PyExc_Fini ((void(*)(void))imports[603].proc)
#define _PyImport_Fini ((void(*)(void))imports[604].proc)
#define PyMethod_Fini ((void(*)(void))imports[605].proc)
#define PyFrame_Fini ((void(*)(void))imports[606].proc)
#define PyCFunction_Fini ((void(*)(void))imports[607].proc)
#define PyDict_Fini ((void(*)(void))imports[608].proc)
#define PyTuple_Fini ((void(*)(void))imports[609].proc)
#define PyList_Fini ((void(*)(void))imports[610].proc)
#define PySet_Fini ((void(*)(void))imports[611].proc)
#define PyString_Fini ((void(*)(void))imports[612].proc)
#define PyInt_Fini ((void(*)(void))imports[613].proc)
#define PyFloat_Fini ((void(*)(void))imports[614].proc)
#define PyOS_FiniInterrupts ((void(*)(void))imports[615].proc)
#define PyByteArray_Fini ((void(*)(void))imports[616].proc)
#define PyOS_Readline ((char*(*)(FILE *, FILE *, char *))imports[617].proc)
#define PyOS_CheckStack ((int(*)(void))imports[618].proc)
#define PyOS_sighandler_tPyOS_getsig ((int(*)(int))imports[619].proc)
#define PyOS_sighandler_tPyOS_setsig ((int(*)(int, PyOS_sighandler_t))imports[620].proc)
#define PyEval_CallObjectWithKeywords ((PyObject*(*)(PyObject *, PyObject *, PyObject *))imports[621].proc)
#define PyEval_CallFunction ((PyObject*(*)(PyObject *obj, const char *format, ...))imports[622].proc)
#define PyEval_CallMethod ((PyObject*(*)(PyObject *obj, const char *methodname, const char *format, ...))imports[623].proc)
#define PyEval_SetProfile ((void(*)(Py_tracefunc, PyObject *))imports[624].proc)
#define PyEval_SetTrace ((void(*)(Py_tracefunc, PyObject *))imports[625].proc)
#define PyEval_GetBuiltins ((PyObject*(*)(void))imports[626].proc)
#define PyEval_GetGlobals ((PyObject*(*)(void))imports[627].proc)
#define PyEval_GetLocals ((PyObject*(*)(void))imports[628].proc)
#define PyEval_GetFrame ((struct _frame*(*)(void))imports[629].proc)
#define PyEval_GetRestricted ((int(*)(void))imports[630].proc)
#define PyEval_MergeCompilerFlags ((int(*)(PyCompilerFlags *cf))imports[631].proc)
#define Py_FlushLine ((int(*)(void))imports[632].proc)
#define Py_AddPendingCall ((int(*)(int (*func)(void *), void *arg))imports[633].proc)
#define Py_MakePendingCalls ((int(*)(void))imports[634].proc)
#define Py_SetRecursionLimit ((void(*)(int))imports[635].proc)
#define Py_GetRecursionLimit ((int(*)(void))imports[636].proc)
#define _Py_CheckRecursiveCall ((int(*)(char *where))imports[637].proc)
#define PyEval_GetFuncName ((const char*(*)(PyObject *))imports[638].proc)
#define PyEval_GetFuncDesc ((const char*(*)(PyObject *))imports[639].proc)
#define PyEval_GetCallStats ((PyObject*(*)(PyObject *))imports[640].proc)
#define PyEval_EvalFrame ((PyObject*(*)(struct _frame *))imports[641].proc)
#define PyEval_EvalFrameEx ((PyObject*(*)(struct _frame *f, int exc))imports[642].proc)
#define PyEval_SaveThread ((PyThreadState*(*)(void))imports[643].proc)
#define PyEval_RestoreThread ((void(*)(PyThreadState *))imports[644].proc)
#define PyEval_ThreadsInitialized ((int(*)(void))imports[645].proc)
#define PyEval_InitThreads ((void(*)(void))imports[646].proc)
#define PyEval_AcquireLock ((void(*)(void))imports[647].proc)
#define PyEval_ReleaseLock ((void(*)(void))imports[648].proc)
#define PyEval_AcquireThread ((void(*)(PyThreadState *tstate))imports[649].proc)
#define PyEval_ReleaseThread ((void(*)(PyThreadState *tstate))imports[650].proc)
#define PyEval_ReInitThreads ((void(*)(void))imports[651].proc)
#define _PyEval_SliceIndex ((int(*)(PyObject *, Py_ssize_t *))imports[652].proc)
#define PySys_GetObject ((PyObject*(*)(char *))imports[653].proc)
#define PySys_SetObject ((int(*)(char *, PyObject *))imports[654].proc)
#define PySys_GetFile ((FILE*(*)(char *, FILE *))imports[655].proc)
#define PySys_SetArgv ((void(*)(int, char **))imports[656].proc)
#define PySys_SetArgvEx ((void(*)(int, char **, int))imports[657].proc)
#define PySys_SetPath ((void(*)(char *))imports[658].proc)
#define PySys_WriteStdout ((void(*)(const char *format, ...))imports[659].proc)
#define PySys_WriteStderr ((void(*)(const char *format, ...))imports[660].proc)
#define PySys_ResetWarnOptions ((void(*)(void))imports[661].proc)
#define PySys_AddWarnOption ((void(*)(char *))imports[662].proc)
#define PySys_HasWarnOptions ((int(*)(void))imports[663].proc)
#define PyOS_InterruptOccurred ((int(*)(void))imports[664].proc)
#define PyOS_InitInterrupts ((void(*)(void))imports[665].proc)
#define PyOS_AfterFork ((void(*)(void))imports[666].proc)
#define PyImport_GetMagicNumber ((long(*)(void))imports[667].proc)
#define PyImport_ExecCodeModule ((PyObject*(*)(char *name, PyObject *co))imports[668].proc)
#define PyImport_ExecCodeModuleEx ((PyObject*(*)(char *name, PyObject *co, char *pathname))imports[669].proc)
#define PyImport_GetModuleDict ((PyObject*(*)(void))imports[670].proc)
#define PyImport_AddModule ((PyObject*(*)(const char *name))imports[671].proc)
#define PyImport_ImportModule ((PyObject*(*)(const char *name))imports[672].proc)
#define PyImport_ImportModuleNoBlock ((PyObject*(*)(const char *))imports[673].proc)
#define PyImport_ImportModuleLevel ((PyObject*(*)(char *name, PyObject *globals, PyObject *locals, PyObject *fromlist, int level))imports[674].proc)
#define PyImport_GetImporter ((PyObject*(*)(PyObject *path))imports[675].proc)
#define PyImport_Import ((PyObject*(*)(PyObject *name))imports[676].proc)
#define PyImport_ReloadModule ((PyObject*(*)(PyObject *m))imports[677].proc)
#define PyImport_Cleanup ((void(*)(void))imports[678].proc)
#define PyImport_ImportFrozenModule ((int(*)(char *))imports[679].proc)
#define _PyImport_AcquireLock ((void(*)(void))imports[680].proc)
#define _PyImport_ReleaseLock ((int(*)(void))imports[681].proc)
#define _PyImport_FindModule ((struct filedescr*(*)(const char *, PyObject *, char *, size_t, FILE **, PyObject **))imports[682].proc)
#define _PyImport_IsScript ((int(*)(struct filedescr *))imports[683].proc)
#define _PyImport_ReInitLock ((void(*)(void))imports[684].proc)
#define _PyImport_FindExtension ((PyObject*(*)(char *, char *))imports[685].proc)
#define _PyImport_FixupExtension ((PyObject*(*)(char *, char *))imports[686].proc)
#define PyImport_AppendInittab ((int(*)(const char *name, void (*initfunc)(void)))imports[687].proc)
#define PyImport_ExtendInittab ((int(*)(struct _inittab *newtab))imports[688].proc)
#define PyObject_Cmp ((int(*)(PyObject *o1, PyObject *o2, int *result))imports[689].proc)
#define PyObject_Call ((PyObject*(*)(PyObject *callable_object, PyObject *args, PyObject *kw))imports[690].proc)
#define PyObject_CallObject ((PyObject*(*)(PyObject *callable_object, PyObject *args))imports[691].proc)
#define PyObject_CallFunction ((PyObject*(*)(PyObject *callable_object, char *format, ...))imports[692].proc)
#define PyObject_CallMethod ((PyObject*(*)(PyObject *o, char *m, char *format, ...))imports[693].proc)
#define _PyObject_CallFunction_SizeT ((PyObject*(*)(PyObject *callable, char *format, ...))imports[694].proc)
#define _PyObject_CallMethod_SizeT ((PyObject*(*)(PyObject *o, char *name, char *format, ...))imports[695].proc)
#define PyObject_CallFunctionObjArgs ((PyObject*(*)(PyObject *callable, ...))imports[696].proc)
#define PyObject_CallMethodObjArgs ((PyObject*(*)(PyObject *o, PyObject *m, ...))imports[697].proc)
#define PyObject_Type ((PyObject*(*)(PyObject *o))imports[698].proc)
#define PyObject_Size ((Py_ssize_t(*)(PyObject *o))imports[699].proc)
#define PyObject_Length ((Py_ssize_t(*)(PyObject *o))imports[700].proc)
#define _PyObject_LengthHint ((Py_ssize_t(*)(PyObject *o, Py_ssize_t))imports[701].proc)
#define PyObject_GetItem ((PyObject*(*)(PyObject *o, PyObject *key))imports[702].proc)
#define PyObject_SetItem ((int(*)(PyObject *o, PyObject *key, PyObject *v))imports[703].proc)
#define PyObject_DelItemString ((int(*)(PyObject *o, char *key))imports[704].proc)
#define PyObject_DelItem ((int(*)(PyObject *o, PyObject *key))imports[705].proc)
#define PyObject_AsCharBuffer ((int(*)(PyObject *obj, const char **buffer, Py_ssize_t *buffer_len))imports[706].proc)
#define PyObject_CheckReadBuffer ((int(*)(PyObject *obj))imports[707].proc)
#define PyObject_AsReadBuffer ((int(*)(PyObject *obj, const **buffer, Py_ssize_t *buffer_len))imports[708].proc)
#define PyObject_AsWriteBuffer ((int(*)(PyObject *obj, void **buffer, Py_ssize_t *buffer_len))imports[709].proc)
#define PyObject_GetBuffer ((int(*)(PyObject *obj, Py_buffer *view, int flags))imports[710].proc)
#define PyBuffer_GetPointer ((void*(*)(Py_buffer *view, Py_ssize_t *indices))imports[711].proc)
#define PyBuffer_SizeFromFormat ((int(*)(const char *))imports[712].proc)
#define PyBuffer_ToContiguous ((int(*)(void *buf, Py_buffer *view, Py_ssize_t len, char fort))imports[713].proc)
#define PyBuffer_FromContiguous ((int(*)(Py_buffer *view, void *buf, Py_ssize_t len, char fort))imports[714].proc)
#define PyObject_CopyData ((int(*)(PyObject *dest, PyObject *src))imports[715].proc)
#define PyBuffer_IsContiguous ((int(*)(Py_buffer *view, char fort))imports[716].proc)
#define PyBuffer_FillContiguousStrides ((void(*)(int ndims, Py_ssize_t *shape, Py_ssize_t *strides, int itemsize, char fort))imports[717].proc)
#define PyBuffer_FillInfo ((int(*)(Py_buffer *view, PyObject *o, void *buf, Py_ssize_t len, int readonly, int flags))imports[718].proc)
#define PyBuffer_Release ((void(*)(Py_buffer *view))imports[719].proc)
#define PyObject_Format ((PyObject*(*)(PyObject *obj, PyObject *format_spec))imports[720].proc)
#define PyObject_GetIter ((PyObject*(*)(PyObject *))imports[721].proc)
#define PyIter_Next ((PyObject*(*)(PyObject *))imports[722].proc)
#define PyNumber_Check ((int(*)(PyObject *o))imports[723].proc)
#define PyNumber_Add ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[724].proc)
#define PyNumber_Subtract ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[725].proc)
#define PyNumber_Multiply ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[726].proc)
#define PyNumber_Divide ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[727].proc)
#define PyNumber_FloorDivide ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[728].proc)
#define PyNumber_TrueDivide ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[729].proc)
#define PyNumber_Remainder ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[730].proc)
#define PyNumber_Divmod ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[731].proc)
#define PyNumber_Power ((PyObject*(*)(PyObject *o1, PyObject *o2, PyObject *o3))imports[732].proc)
#define PyNumber_Negative ((PyObject*(*)(PyObject *o))imports[733].proc)
#define PyNumber_Positive ((PyObject*(*)(PyObject *o))imports[734].proc)
#define PyNumber_Absolute ((PyObject*(*)(PyObject *o))imports[735].proc)
#define PyNumber_Invert ((PyObject*(*)(PyObject *o))imports[736].proc)
#define PyNumber_Lshift ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[737].proc)
#define PyNumber_Rshift ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[738].proc)
#define PyNumber_And ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[739].proc)
#define PyNumber_Xor ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[740].proc)
#define PyNumber_Or ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[741].proc)
#define PyNumber_Index ((PyObject*(*)(PyObject *o))imports[742].proc)
#define PyNumber_AsSsize_t ((Py_ssize_t(*)(PyObject *o, PyObject *exc))imports[743].proc)
#define _PyNumber_ConvertIntegralToInt ((PyObject*(*)(PyObject *integral, const char *error_format))imports[744].proc)
#define PyNumber_Int ((PyObject*(*)(PyObject *o))imports[745].proc)
#define PyNumber_Long ((PyObject*(*)(PyObject *o))imports[746].proc)
#define PyNumber_Float ((PyObject*(*)(PyObject *o))imports[747].proc)
#define PyNumber_InPlaceAdd ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[748].proc)
#define PyNumber_InPlaceSubtract ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[749].proc)
#define PyNumber_InPlaceMultiply ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[750].proc)
#define PyNumber_InPlaceDivide ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[751].proc)
#define PyNumber_InPlaceFloorDivide ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[752].proc)
#define PyNumber_InPlaceTrueDivide ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[753].proc)
#define PyNumber_InPlaceRemainder ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[754].proc)
#define PyNumber_InPlacePower ((PyObject*(*)(PyObject *o1, PyObject *o2, PyObject *o3))imports[755].proc)
#define PyNumber_InPlaceLshift ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[756].proc)
#define PyNumber_InPlaceRshift ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[757].proc)
#define PyNumber_InPlaceAnd ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[758].proc)
#define PyNumber_InPlaceXor ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[759].proc)
#define PyNumber_InPlaceOr ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[760].proc)
#define PyNumber_ToBase ((PyObject*(*)(PyObject *n, int base))imports[761].proc)
#define PySequence_Check ((int(*)(PyObject *o))imports[762].proc)
#define PySequence_Size ((Py_ssize_t(*)(PyObject *o))imports[763].proc)
#define PySequence_Length ((Py_ssize_t(*)(PyObject *o))imports[764].proc)
#define PySequence_Concat ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[765].proc)
#define PySequence_Repeat ((PyObject*(*)(PyObject *o, Py_ssize_t count))imports[766].proc)
#define PySequence_GetItem ((PyObject*(*)(PyObject *o, Py_ssize_t i))imports[767].proc)
#define PySequence_GetSlice ((PyObject*(*)(PyObject *o, Py_ssize_t i1, Py_ssize_t i2))imports[768].proc)
#define PySequence_SetItem ((int(*)(PyObject *o, Py_ssize_t i, PyObject *v))imports[769].proc)
#define PySequence_DelItem ((int(*)(PyObject *o, Py_ssize_t i))imports[770].proc)
#define PySequence_SetSlice ((int(*)(PyObject *o, Py_ssize_t i1, Py_ssize_t i2, PyObject *v))imports[771].proc)
#define PySequence_DelSlice ((int(*)(PyObject *o, Py_ssize_t i1, Py_ssize_t i2))imports[772].proc)
#define PySequence_Tuple ((PyObject*(*)(PyObject *o))imports[773].proc)
#define PySequence_List ((PyObject*(*)(PyObject *o))imports[774].proc)
#define PySequence_Fast ((PyObject*(*)(PyObject *o, const char *m))imports[775].proc)
#define PySequence_Count ((Py_ssize_t(*)(PyObject *o, PyObject *value))imports[776].proc)
#define PySequence_Contains ((int(*)(PyObject *seq, PyObject *ob))imports[777].proc)
#define _PySequence_IterSearch ((Py_ssize_t(*)(PyObject *seq, PyObject *obj, int operation))imports[778].proc)
#define PySequence_In ((int(*)(PyObject *o, PyObject *value))imports[779].proc)
#define PySequence_Index ((Py_ssize_t(*)(PyObject *o, PyObject *value))imports[780].proc)
#define PySequence_InPlaceConcat ((PyObject*(*)(PyObject *o1, PyObject *o2))imports[781].proc)
#define PySequence_InPlaceRepeat ((PyObject*(*)(PyObject *o, Py_ssize_t count))imports[782].proc)
#define PyMapping_Check ((int(*)(PyObject *o))imports[783].proc)
#define PyMapping_Size ((Py_ssize_t(*)(PyObject *o))imports[784].proc)
#define PyMapping_Length ((Py_ssize_t(*)(PyObject *o))imports[785].proc)
#define PyMapping_HasKeyString ((int(*)(PyObject *o, char *key))imports[786].proc)
#define PyMapping_HasKey ((int(*)(PyObject *o, PyObject *key))imports[787].proc)
#define PyMapping_GetItemString ((PyObject*(*)(PyObject *o, char *key))imports[788].proc)
#define PyMapping_SetItemString ((int(*)(PyObject *o, char *key, PyObject *value))imports[789].proc)
#define PyObject_IsInstance ((int(*)(PyObject *object, PyObject *typeorclass))imports[790].proc)
#define PyObject_IsSubclass ((int(*)(PyObject *object, PyObject *typeorclass))imports[791].proc)
#define _PyObject_RealIsInstance ((int(*)(PyObject *inst, PyObject *cls))imports[792].proc)
#define _PyObject_RealIsSubclass ((int(*)(PyObject *derived, PyObject *cls))imports[793].proc)
#define _Py_add_one_to_index_F ((void(*)(int nd, Py_ssize_t *index, const Py_ssize_t *shape))imports[794].proc)
#define _Py_add_one_to_index_C ((void(*)(int nd, Py_ssize_t *index, const Py_ssize_t *shape))imports[795].proc)
#define PyCode_New ((PyCodeObject*(*)(int, int, int, int, PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, int, PyObject *))imports[796].proc)
#define PyCode_NewEmpty ((PyCodeObject*(*)(const char *filename, const char *funcname, int firstlineno))imports[797].proc)
#define PyCode_Addr2Line ((int(*)(PyCodeObject *, int))imports[798].proc)
#define _PyCode_CheckLineNumber ((int(*)(PyCodeObject *co, int lasti, PyAddrPair *bounds))imports[799].proc)
#define PyCode_Optimize ((PyObject*(*)(PyObject *code, PyObject *consts, PyObject *names, PyObject *lineno_obj))imports[800].proc)
#define PyNode_Compile ((PyCodeObject*(*)(struct _node *, const char *))imports[801].proc)
#define PyAST_Compile ((PyCodeObject*(*)(struct _mod *, const char *, PyCompilerFlags *, PyArena *))imports[802].proc)
#define PyFuture_FromAST ((PyFutureFeatures*(*)(struct _mod *, const char *))imports[803].proc)
#define PyEval_EvalCode ((PyObject*(*)(PyCodeObject *, PyObject *, PyObject *))imports[804].proc)
#define PyEval_EvalCodeEx ((PyObject*(*)(PyCodeObject *co, PyObject *globals, PyObject *locals, PyObject **args, int argc, PyObject **kwds, int kwdc, PyObject **defs, int defc, PyObject *closure))imports[805].proc)
#define _PyEval_CallTracing ((PyObject*(*)(PyObject *func, PyObject *args))imports[806].proc)
#define PyOS_ascii_strtod ((double(*)(const char *str, char **ptr))imports[807].proc)
#define PyOS_ascii_atof ((double(*)(const char *str))imports[808].proc)
#define PyOS_ascii_formatd ((char*(*)(char *buffer, size_t buf_len, const char *format, double d))imports[809].proc)
#define PyOS_string_to_double ((double(*)(const char *str, char **endptr, PyObject *overflow_exception))imports[810].proc)
#define PyOS_double_to_string ((char*(*)(double val, char format_code, int precision, int flags, int *type))imports[811].proc)
#define _Py_parse_inf_or_nan ((double(*)(const char *p, char **endptr))imports[812].proc)
#define PyOS_mystrnicmp ((int(*)(const char *, const char *, Py_ssize_t))imports[813].proc)
#define PyOS_mystricmp ((int(*)(const char *, const char *))imports[814].proc)
#define _Py_dg_strtod ((double(*)(const char *str, char **ptr))imports[815].proc)
#define _Py_dg_dtoa ((char*(*)(double d, int mode, int ndigits, int *decpt, int *sign, char **rve))imports[816].proc)
#define _Py_dg_freedtoa ((void(*)(char *s))imports[817].proc)
#define _Py_Mangle ((PyObject*(*)(PyObject *p, PyObject *name))imports[818].proc)
#define _Py_NoneStruct (*((PyObject*)imports[819].proc))
#define _Py_NotImplementedStruct (*((PyObject)imports[820].proc))
#define _Py_TrueStruct (*((PyObject*)imports[821].proc))
#define _Py_ZeroStruct (*((PyObject*)imports[822].proc))
#define PyList_Type (*((PyTypeObject*)imports[823].proc))
#define PyTuple_Type (*((PyTypeObject*)imports[824].proc))
#define PyString_Type (*((PyTypeObject*)imports[825].proc))
#define _PyThreadState_Current ((PyThreadState*)imports[826].proc)
#define PyFrame_New ((PyFrameObject*(*)(PyThreadState *, PyCodeObject *, PyObject *, PyObject *))imports[827].proc)
#define PyClass_Type (*((PyTypeObject*)imports[828].proc))
#define PyInstance_Type (*((PyTypeObject*)imports[829].proc))
#define PyMethod_Type (*((PyTypeObject*)imports[830].proc))

#define PyExc_BaseException ((PyObject *)imports[831].proc)
#define PyExc_Exception ((PyObject *)imports[832].proc)
#define PyExc_StopIteration ((PyObject *)imports[833].proc)
#define PyExc_GeneratorExit ((PyObject *)imports[834].proc)
#define PyExc_StandardError ((PyObject *)imports[835].proc)
#define PyExc_ArithmeticError ((PyObject *)imports[836].proc)
#define PyExc_LookupError ((PyObject *)imports[837].proc)
#define PyExc_AssertionError ((PyObject *)imports[838].proc)
#define PyExc_AttributeError ((PyObject *)imports[839].proc)
#define PyExc_EOFError ((PyObject *)imports[840].proc)
#define PyExc_FloatingPointError ((PyObject *)imports[841].proc)
#define PyExc_EnvironmentError ((PyObject *)imports[842].proc)
#define PyExc_IOError ((PyObject *)imports[843].proc)
#define PyExc_OSError ((PyObject *)imports[844].proc)
#define PyExc_ImportError ((PyObject *)imports[845].proc)
#define PyExc_IndexError ((PyObject *)imports[846].proc)
#define PyExc_KeyError ((PyObject *)imports[847].proc)
#define PyExc_KeyboardInterrupt ((PyObject *)imports[848].proc)
#define PyExc_MemoryError ((PyObject *)imports[849].proc)
#define PyExc_NameError ((PyObject *)imports[850].proc)
#define PyExc_OverflowError ((PyObject *)imports[851].proc)
#define PyExc_RuntimeError ((PyObject *)imports[852].proc)
#define PyExc_NotImplementedError ((PyObject *)imports[853].proc)
#define PyExc_SyntaxError ((PyObject *)imports[854].proc)
#define PyExc_IndentationError ((PyObject *)imports[855].proc)
#define PyExc_TabError ((PyObject *)imports[856].proc)
#define PyExc_ReferenceError ((PyObject *)imports[857].proc)
#define PyExc_SystemError ((PyObject *)imports[858].proc)
#define PyExc_SystemExit ((PyObject *)imports[859].proc)
#define PyExc_TypeError ((PyObject *)imports[860].proc)
#define PyExc_UnboundLocalError ((PyObject *)imports[861].proc)
#define PyExc_UnicodeError ((PyObject *)imports[862].proc)
#define PyExc_UnicodeEncodeError ((PyObject *)imports[863].proc)
#define PyExc_UnicodeDecodeError ((PyObject *)imports[864].proc)
#define PyExc_UnicodeTranslateError ((PyObject *)imports[865].proc)
#define PyExc_ValueError ((PyObject *)imports[866].proc)
#define PyExc_ZeroDivisionError ((PyObject *)imports[867].proc)
#define PyExc_WindowsError ((PyObject *)imports[868].proc)
#define PyExc_BufferError ((PyObject *)imports[869].proc)
#define PyExc_MemoryErrorInst ((PyObject *)imports[870].proc)
#define PyExc_RecursionErrorInst ((PyObject *)imports[871].proc)
#define PyExc_Warning ((PyObject *)imports[872].proc)
#define PyExc_UserWarning ((PyObject *)imports[873].proc)
#define PyExc_DeprecationWarning ((PyObject *)imports[874].proc)
#define PyExc_PendingDeprecationWarning ((PyObject *)imports[875].proc)
#define PyExc_SyntaxWarning ((PyObject *)imports[876].proc)
#define PyExc_RuntimeWarning ((PyObject *)imports[877].proc)
#define PyExc_FutureWarning ((PyObject *)imports[878].proc)
#define PyExc_ImportWarning ((PyObject *)imports[879].proc)
#define PyExc_UnicodeWarning ((PyObject *)imports[880].proc)
#define PyExc_BytesWarning ((PyObject *)imports[881].proc).
#define PyUnicode_Type ((PyTypeObject *)imports[881].proc)
